services:
  - type: web
    name: fire-noc
    env: python
    region: singapore
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr wkhtmltopdf python3-dev build-essential
      python -m pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt --no-cache-dir
    startCommand: gunicorn 'wsgi:app'
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://mkbharvad8080:Mkb%408080@cluster0.a82h2.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: PORT
        value: 8000
      - key: NODE_ENV
        value: production
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        value: mkbharvad534@gmail.com
      - key: MAIL_PASSWORD
        value: dwtp fmiq miyl ccvq
      - key: JWT_SECRET_KEY
        value: your_jwt_secret_here
      - key: FIREBASE_API_KEY
        value: your_firebase_api_key
      - key: GOOGLE_MAPS_API_KEY
        value: your_google_maps_api_key
      - key: TESSERACT_CMD
        value: /usr/bin/tesseract
      - key: LOG_LEVEL
        value: INFO
      - key: PYTHONUNBUFFERED
        value: "true"
    python_version: 3.9.0
    plan: starter
    buildFilter:
      paths:
      - requirements.txt
      - fire/**
      - static/**
      - templates/**
      - "*.py"
    healthCheckPath: /health
    healthCheck:
      path: /health
      interval: 15s
      timeout: 5s
      retries: 3
    autoDeploy: true
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
    domains:
      - fire-noc.onrender.com
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 75
    resources:
      cpu: 1x
      memory: 512MB
      storage: 512MB
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
