services:
  - type: web
    name: fire-noc
    env: python
    buildCommand: pip install -r requirements.txt && npm install
    startCommand: gunicorn fire.app:app
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://mkbharvad8080:Mkb%408080@cluster0.a82h2.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: PORT
        value: 8000
      - key: NODE_ENV
        value: production
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        value: mkbharvad534@gmail.com
      - key: MAIL_PASSWORD
        value: dwtp fmiq miyl ccvq
